/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Form_I01 extends javax.swing.JFrame {

    /**
     * Creates new form Form_I01
     */
    public Form_I01() {
        initComponents();

    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stu_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        stu_address = new javax.swing.JTextField();
        stu_home_phone = new javax.swing.JTextField();
        stu_mobile_phone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        stu_cgpa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        stu_semester = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        stu_year = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        stu_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stu_email = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Faculty Of Computing");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Form I-1 (Part 1)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Internship Acceptance Form");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 270, 30));

        jLabel6.setText("Student ID No");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));
        getContentPane().add(stu_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 460, -1));

        jLabel7.setText("Email Addresses");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 120, -1));

        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 110, -1));

        jLabel10.setText("Home Phone");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, -1));

        jLabel11.setText("Mobile Phone");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 110, -1));
        getContentPane().add(stu_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 610, -1));
        getContentPane().add(stu_home_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 610, -1));
        getContentPane().add(stu_mobile_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 610, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("*Use a Comma(,) to seperate multiple e-mail addresses");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jLabel13.setText("CGPA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 60, -1));
        getContentPane().add(stu_cgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 90, -1));

        jLabel14.setText("Semester");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));
        getContentPane().add(stu_semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 90, -1));

        jLabel15.setText("Year");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 60, -1));
        getContentPane().add(stu_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 90, -1));

        jLabel16.setText("(To be filled by student)");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel17.setText("Student's Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        getContentPane().add(stu_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 610, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Submit to Employer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        stu_email.setColumns(20);
        stu_email.setRows(5);
        jScrollPane1.setViewportView(stu_email);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 610, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String student_id=stu_id.getText();
        String student_name=stu_name.getText();
        String student_address=stu_address.getText();
        String student_home_phone=stu_home_phone.getText();
        String student_mobile_phone=stu_mobile_phone.getText();
        String student_email=stu_email.getText();
        String student_semester=stu_semester.getText();
        String student_year=stu_year.getText();
        String student_cgpa=stu_cgpa.getText();
        
        if((student_id.length()==0)||(student_name.length()==0)||(student_address.length()==0)||(student_home_phone.length()==0)||(student_mobile_phone.length()==0)
                ||(student_email.length()==0)||(student_semester.length()==0)||(student_year.length()==0)||(student_cgpa.length()==0)){
                     JOptionPane.showMessageDialog(null, "Fill all fields");
        }
        else if(!student_id.startsWith("IT")){
            JOptionPane.showMessageDialog(null, "Invalid IT number");
        }
        else if((student_home_phone.length()!=10)&&(student_mobile_phone.length()!=10)){
            JOptionPane.showMessageDialog(null, "Invalid phone number");
        }
        else if((!student_email.endsWith(".com"))||(!student_email.endsWith(".lk"))||(!student_email.contains("@"))){
            JOptionPane.showMessageDialog(null, "Invalid email address");
        }
        else if((student_semester.length()!=1)){
            JOptionPane.showMessageDialog(null, "Invalid semester");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_I01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_I01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_I01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_I01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_I01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stu_address;
    private javax.swing.JTextField stu_cgpa;
    private javax.swing.JTextArea stu_email;
    private javax.swing.JTextField stu_home_phone;
    private javax.swing.JTextField stu_id;
    private javax.swing.JTextField stu_mobile_phone;
    private javax.swing.JTextField stu_name;
    private javax.swing.JTextField stu_semester;
    private javax.swing.JTextField stu_year;
    // End of variables declaration//GEN-END:variables
}
