/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import MainFiles.Dbconfig;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Form_I01 extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    /**
     * Creates new form Form_I01
     */
    public Form_I01() {
        initComponents();
         con=Dbconfig.connect();

    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stu_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        stu_address = new javax.swing.JTextField();
        stu_home_phone = new javax.swing.JTextField();
        stu_mobile_phone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        stu_cgpa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        stu_semester = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        stu_year = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        stu_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stu_email = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Faculty Of Computing");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Form I-1 (Part 1)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Internship Acceptance Form");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 270, 30));

        jLabel6.setText("Student ID No");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));
        getContentPane().add(stu_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 460, -1));

        jLabel7.setText("Email Addresses");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 120, -1));

        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 110, -1));

        jLabel10.setText("Home Phone");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, -1));

        jLabel11.setText("Mobile Phone");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 110, -1));
        getContentPane().add(stu_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 610, -1));
        getContentPane().add(stu_home_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 610, -1));
        getContentPane().add(stu_mobile_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 610, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("*Use a Comma(,) to seperate multiple e-mail addresses");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jLabel13.setText("CGPA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 60, -1));
        getContentPane().add(stu_cgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 90, -1));

        jLabel14.setText("Semester");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));
        getContentPane().add(stu_semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 90, -1));

        jLabel15.setText("Year");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 60, -1));
        getContentPane().add(stu_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 90, -1));

        jLabel16.setText("(To be filled by student)");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel17.setText("Student's Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        getContentPane().add(stu_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 610, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Submit to Employer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        stu_email.setColumns(20);
        stu_email.setRows(5);
        jScrollPane1.setViewportView(stu_email);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 610, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String student_id_=stu_id.getText();
        String student_name_=stu_name.getText();
        String student_address_=stu_address.getText();
        int student_home_phone_=Integer.parseInt(stu_home_phone.getText());
        int student_mobile_phone_=Integer.parseInt(stu_mobile_phone.getText());
        String student_email_=stu_email.getText();
        int student_semester_=Integer.parseInt(stu_semester.getText());
        int student_year_=Integer.parseInt(stu_year.getText());
        float student_cgpa_=Float.parseFloat(stu_cgpa.getText());
        
     /*   if((student_id_.isEmpty())||(student_name_.isEmpty())||(student_address_.isEmpty())||(student_home_phone_.isEmpty())||(student_mobile_phone_.isEmpty())
                ||(student_email_.isEmpty())||(student_semester_.isEmpty())||(student_year_.isEmpty())||(student_cgpa_.isEmpty())){
                     JOptionPane.showMessageDialog(null, "Fill all fields");
        }
        else if(!student_id_.startsWith("IT")){
            JOptionPane.showMessageDialog(null, "Invalid IT number");
        }
        else if((student_home_phone_.length()!=10)&&(student_mobile_phone_.length()!=10)){
            JOptionPane.showMessageDialog(null, "Invalid phone number");
        }
        else if(student_email_.indexOf('@')==0 || student_email_.indexOf('.')==0 ||student_email_.indexOf('@')>student_email_.indexOf('.')){
            JOptionPane.showMessageDialog(null, "Invalid email address");
        }
        else if((student_semester_.length()!=1)){
            JOptionPane.showMessageDialog(null, "Invalid semester");
        }
        else{*/
        System.out.println("1st");
            try{
                 String q="Insert into form_i-01(student_id,student_name,"
               + "student_address,student_home_phone,student_mobile_phone,"
               + "student_email,student_semester,student_year,student_cgpa)"
               + "values('"+student_id_+"','"+student_name_+"','"+student_address_+"'"
               + ",'"+student_home_phone_+"','"+student_mobile_phone_+"',"
               + "'"+student_email_+"','"+student_semester_+"',"
                         + "'"+student_year_+"','"+student_cgpa_+"')";
                System.out.println("2nd");
              pst=(PreparedStatement) con.prepareStatement(q);
                 System.out.println("3rd");
              pst.execute();
                 
                 System.out.println("4th");
                JOptionPane.showMessageDialog(null, "successfully added");
                
            }catch(Exception e){
                e.getMessage();
            }
      //  }
        
           /*  stu_id.setText("");
             stu_name.setText("");
               stu_address.setText("");  
              stu_home_phone.setText("");  
              stu_mobile_phone.setText("");
             stu_email.setText("");
              stu_semester.setText("");
              stu_year.setText("");
              stu_cgpa.setText("");*/
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_I01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_I01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_I01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_I01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_I01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stu_address;
    private javax.swing.JTextField stu_cgpa;
    private javax.swing.JTextArea stu_email;
    private javax.swing.JTextField stu_home_phone;
    private javax.swing.JTextField stu_id;
    private javax.swing.JTextField stu_mobile_phone;
    private javax.swing.JTextField stu_name;
    private javax.swing.JTextField stu_semester;
    private javax.swing.JTextField stu_year;
    // End of variables declaration//GEN-END:variables
}
