/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.io.File;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.Address;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Pavani
 */
public class Reject_mail extends javax.swing.JFrame {

    /**
     * Creates new form Reject_mail
     */
    public Reject_mail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtTo = new javax.swing.JTextField();
        TxtSubject = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAText = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        BTSend = new javax.swing.JButton();
        BTAttach = new javax.swing.JButton();
        path = new javax.swing.JLabel();
        name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(TxtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 180, -1));
        getContentPane().add(TxtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 180, -1));

        jTextField3.setText("To");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, -1));

        jTextField4.setText("Attach");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 60, -1));

        jTextField5.setText("Subject");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 60, -1));

        TxtAText.setColumns(20);
        TxtAText.setRows(5);
        jScrollPane1.setViewportView(TxtAText);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 180, 120));

        jTextField6.setText("Text");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 60, -1));

        BTSend.setText("Send");
        BTSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSendActionPerformed(evt);
            }
        });
        getContentPane().add(BTSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        BTAttach.setText("Attach");
        BTAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAttachActionPerformed(evt);
            }
        });
        getContentPane().add(BTAttach, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));
        getContentPane().add(path, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 110, 40));

        name.setText("jTextField1");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 330, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void BTAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAttachActionPerformed
        // TODO add your handling code here:
         JFileChooser filechooser = new JFileChooser();
        filechooser.showOpenDialog(null);
        File f = filechooser.getSelectedFile();
        attachment_path=f.getAbsolutePath();
        path.setText(attachment_path);
       
    }//GEN-LAST:event_BTAttachActionPerformed

    private void BTSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSendActionPerformed
        // TODO add your handling code here:
        
          Properties props  = new  Properties();
        props.put("mail.smtp.host","smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port","465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth",true);
        props.put("mail.smtp.port","465");

        Session sess = Session.getDefaultInstance(props,
            new javax.mail.Authenticator(){
                protected PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication("pavanisubasinghe123@gmail.com","pavani123");
                }
            });
        System.out.println("authenticate success");
            try{

                String text = TxtAText.getText();
                String To = TxtTo.getText();
                String Subject = TxtSubject.getText();
                
                Message message = new MimeMessage(sess);
                message.setFrom(new InternetAddress("pavanisubasinghe123@gmail.com"));
               message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(To));
               //message.setRecipients(Message.RecipientType.TO, InternetAddress.parse("sithara.liyanaarachchi@gmail.com"));
                message.setSubject(Subject);
               message.setText(text);       
                                   
                 System.out.println("01");
                MimeBodyPart msgbodypart = new MimeBodyPart();
                msgbodypart.setText(text);
                Multipart multipart = new MimeMultipart();
                multipart.addBodyPart(msgbodypart);
                
                 System.out.println("02");
                 
                msgbodypart=new MimeBodyPart();
                javax.activation.DataSource source = new FileDataSource(attachment_path);
                msgbodypart.setDataHandler(new DataHandler(source));
                msgbodypart.setFileName(name.getText());
                multipart.addBodyPart(msgbodypart);
                message.setContent(multipart);
                    
                        System.out.println("03"); 
                          
                Transport.send(message);
                 System.out.println("04"); 
                JOptionPane.showMessageDialog(null, "Successfully sent e-mail");
                 System.out.println("05"); 
            }catch(Exception e)
            {

            }
    }//GEN-LAST:event_BTSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reject_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reject_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reject_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reject_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reject_mail().setVisible(true);
            }
        });
    }
String attachment_path;
String attachment_target_path;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAttach;
    private javax.swing.JButton BTSend;
    private javax.swing.JTextArea TxtAText;
    private javax.swing.JTextField TxtSubject;
    private javax.swing.JTextField TxtTo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField name;
    private javax.swing.JLabel path;
    // End of variables declaration//GEN-END:variables
}
