/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import MainFiles.Dbconfig;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Reset_form extends javax.swing.JFrame {
        Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    /**
     * Creates new form Reset_form
     */
    public Reset_form() {
        initComponents();
        con=Dbconfig.connect();
        newpw.setVisible(false);
        conpw.setVisible(false);
        newpwl.setVisible(false);
        conpwl.setVisible(false);
        reset.setVisible(false);
        student.setVisible(true);
        employer.setVisible(true);
        ButtonGroup group =new ButtonGroup();
        group.add(student);
        group.add(employer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        newpwl = new javax.swing.JLabel();
        newpw = new javax.swing.JTextField();
        conpwl = new javax.swing.JLabel();
        conpw = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        employer = new javax.swing.JRadioButton();
        student = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 78, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 240, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("Next >");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 90, -1));

        newpwl.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        newpwl.setText("new Password");
        getContentPane().add(newpwl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 120, -1));
        getContentPane().add(newpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 340, -1));

        conpwl.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        conpwl.setText("Confirm Password");
        getContentPane().add(conpwl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 150, -1));
        getContentPane().add(conpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 340, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Reset Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 250, -1));

        reset.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 90, -1));

        employer.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        employer.setText("I am an employer");
        getContentPane().add(employer, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        student.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        student.setText("I am a student");
        getContentPane().add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Select User Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton2.setText("< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/S_images/reset-icon.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 110, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email_ =email.getText();
        
        if((email_.length()==0))
        {
            
                JOptionPane.showMessageDialog(null, "Fill all fields");
        }
        else if(email_.indexOf('@')==0 || email_.indexOf('.')==0 ||email_.indexOf('@')>email_.indexOf('.')){
            JOptionPane.showMessageDialog(null, "invalid email format");
        }
        else{
            if(student.isSelected()){
            String sql="select * from student_login where  email=? ";
            try{
                
                pst=con.prepareStatement(sql);
                pst.setString(1,email.getText());
                rs=pst.executeQuery();
                
                if(rs.next())
                {
                        JOptionPane.showMessageDialog(null, "Correct Email");
                        newpw.setVisible(true);
                        conpw.setVisible(true);
                        newpwl.setVisible(true);
                        conpwl.setVisible(true);
                        reset.setVisible(true);
                        student.setVisible(true);
                        employer.setVisible(true);
 
                }
                else{
                    JOptionPane.showMessageDialog(null, "Invalid Email");
                }
                
            }catch(Exception e){
                e.getMessage();
            }
            
            }
            else{
                    String sql="select * from login where  email=? ";
                    try{
                
                        pst=con.prepareStatement(sql);
                        pst.setString(1,email.getText());
                        rs=pst.executeQuery();
                
                        if(rs.next())
                        {
                            JOptionPane.showMessageDialog(null, "Correct Email");
                            newpw.setVisible(true);
                            conpw.setVisible(true);
                            newpwl.setVisible(true);
                            conpwl.setVisible(true);
                            reset.setVisible(true);
                            student.setVisible(true);
                            employer.setVisible(true);
 
                }
                else{
                    JOptionPane.showMessageDialog(null, "Invalid Email");
                }
                
            }catch(Exception e){
                e.getMessage();
            }
            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        String email_=email.getText();
        int x=JOptionPane.showConfirmDialog(null,"Do you really want to reset password");
        
        if(x==0){
            
            String newpassword=newpw.getText();
            String confirmpassword=conpw.getText();
            
            if(student.isSelected()){
             String sql="Update student_login set password='"+newpassword+"'where email='"+email_+"'";
             
             try{
                 
                pst=(PreparedStatement) con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(this, "You successfully reset your password");
                
             }catch(Exception e){
                 e.getMessage();
             }
            }
            else{
                String sql="Update login set password='"+newpassword+"' where email='"+email_+"'";
             
                try{
                 
                    pst=(PreparedStatement) con.prepareStatement(sql);
                    pst.execute();
                    
                    JOptionPane.showMessageDialog(this, "You successfully reset your password");
                
                    }catch(Exception e){
                        e.getMessage();
                    }
                }
             
             newpw.setText("");
             conpw.setText("");
             email.setText("");
             student.setSelected(false);
             employer.setSelected(false);
           
            
        }
        
    }//GEN-LAST:event_resetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login l=new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reset_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reset_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reset_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reset_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reset_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField conpw;
    private javax.swing.JLabel conpwl;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton employer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField newpw;
    private javax.swing.JLabel newpwl;
    private javax.swing.JButton reset;
    private javax.swing.JRadioButton student;
    // End of variables declaration//GEN-END:variables
}
